### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by DanBaDo** [alfonsoporto22/Project#1]
https://github.com/alfonsoporto22/Project/blob/406c34c76eaabafc101ae25f4f3242fef3bed690/project/README.md?plain=1#L24-L36

Necesito que trabajes un poco más la parte del mockup. Que tenga un aspecto un poco más cercano a lo que se vería en una pantalla.

No tiene que ser "realista" pero que se diferencien cláramente listas, botones, menues... y el diferente aspecto de la pantalla con los menúes abiertos y cerrados, las diferentes pantallas de los diferentes procesos del usuario (login, confirmación compra...).

**Comment by alfonsoporto22** [comment]
Hecho! Un saludo
